/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author jojo
 */
public class farmerpurchase extends javax.swing.JFrame {

    /**
     * Creates new form farmerpurchase
     */
     Connection conn=null;
     Date date = new Date();
     DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
 
        //to convert Date to String, use format method of SimpleDateFormat class.
        String strDate = dateFormat.format(date);
         public farmerpurchase() {
        initComponents();
        jTextField1.setText(strDate); 
        
    }
         
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rb.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iso.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("LOGOUT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel21.setText("Farmer Purchase");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("FARMER PURCHASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PURCHASE");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SALES");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("DEALER SALES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD USER");

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("HOME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("FARMER PURCHASE LIST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("DEALER SALES LIST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("ADD FARMER USER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setText("ADD SALES LIST");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(41, 41, 41))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Purchase date");

        jTextField1.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Purchase Numeber");

        jTextField2.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Deatails of Supplier");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Shipped From");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Commodity Code");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Item" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("HSN Code");

        jTextField3.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Number of Barrels");

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Wet.Weight(Kg)");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("DRC%");

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("DRC Wet Kgs");

        jTextField7.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Rate");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Total");

        jTextField10.setEditable(false);

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 204, 0));
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 204, 0));
        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Name");

        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField6))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField10)
                            .addComponent(jTextField7)
                            .addComponent(jTextField5))
                        .addGap(193, 193, 193))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(jComboBox1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new userhome().setVisible(true); 
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new farmerpurchase().setVisible(true); 
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       new salesdealer().setVisible(true); 
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
      new login().setVisible(true); 
      dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
    conn = dbconnection.getConnected();
    Statement st =  conn.createStatement();
    Statement st1 = conn.createStatement();
    
            ResultSet rs;
            rs = st.executeQuery("SELECT MAX(fid) FROM farmerpurchase");
            ResultSet rs1;
            rs1 = st1.executeQuery("SELECT commoditycode  FROM  commoditycode");
            
    if (rs.next()) {
        int billNumber = rs.getInt(1) + 1;
        jTextField2.setText(Integer.toString(billNumber));
        }
          while ((rs1.next())) {
            jComboBox1.addItem(rs1.getString("commoditycode"));
          }
    
          
    conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }
    
    }//GEN-LAST:event_formWindowOpened

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextField1.setText(strDate);
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField9.setText("");
        jTextArea1.setText("");
        
    }//GEN-LAST:event_jButton8ActionPerformed

    
    
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       
        conn = dbconnection.getConnected();
        String purdate, purnumber,detailsupp,shippedfrom,commoditycode,hsncode,noofbarrels,wetwg,drc,drcwtkgs,rate,total,name,ramount;
        purdate =this.jTextField1.getText();
        purnumber = this.jTextField2.getText();
        detailsupp = this.jTextArea1.getText();
        shippedfrom = this.jTextArea2.getText();
        commoditycode = (String) this.jComboBox1.getSelectedItem();
        hsncode = this.jTextField3.getText();
        noofbarrels = this.jTextField4.getText();
//        NumberFormatter formatter = new NumberFormatter(); //create the formatter
//        formatter.setAllowsInvalid(false); //must specify that invalid chars are not allowed
//        JFormattedTextField jTextField4 = new JFormattedTextField(formatter);
        wetwg = this.jTextField5.getText();
        drc = this.jTextField6.getText();
        drcwtkgs=this.jTextField7.getText();
        rate=this.jTextField8.getText();
        total=this.jTextField10.getText();
        name=this.jTextField9.getText();
        
        ramount="0.0";
        //total=Math.round(total);
        System.out.println(total + purdate + purnumber + detailsupp + shippedfrom + commoditycode + hsncode + noofbarrels + wetwg + drc + drcwtkgs + rate+name);
        String query;
        try {
            query = "insert into farmerpurchase(purdate,purnumber,detailsupp,shippedfrom,commoditycode,hsncode,noofbarrels,wetwg,drc,drcwtkgs,rate,total,name,ramount)  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst= conn.prepareStatement(query);
            pst.setString(1,purdate);
            pst.setString(2,purnumber);
            pst.setString(3,detailsupp);
            pst.setString(4,shippedfrom);
            pst.setString(5,commoditycode);
            pst.setString(6,hsncode);
            pst.setString(7,noofbarrels);
            pst.setString(8,wetwg);
            pst.setString(9,drc);
            pst.setString(10,drcwtkgs);
            pst.setString(11,rate);
            pst.setString(12,total);
            pst.setString(13,name);
            pst.setString(14,ramount);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Updated");
            jTextField1.setText("");
            int purnumnext=Integer.parseInt(purnumber)+1;
            jTextField2.setText(Integer.toString(purnumnext));
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField10.setText("");
            jTextField9.setText("");
            jTextArea1.setText("");
            jTextArea2.setText("");

            jTextField1.setText(strDate);
            DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
     
           
        } catch (SQLException ex) {
            
            Logger.getLogger(farmerpurchase.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Please Insert Value");
            
        }
               try{
            Document document=new Document();
            PdfWriter.getInstance(document, new FileOutputStream("pdfresult/result.pdf"));
            document.open();
            PdfPTable table=new PdfPTable(1);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Phrase("                                                                                          "));
            cell.addElement(new Paragraph("                                                               Company Name              ", FontFactory.getFont(FontFactory.TIMES_ROMAN,14, Font.BOLD, BaseColor.BLACK)));
            cell.addElement(new Paragraph("                            Place P O, Palce ROAD            ", FontFactory.getFont(FontFactory.COURIER,10, Font.NORMAL , BaseColor.BLACK)));
            cell.addElement(new Paragraph("                            Distritc DIST, State, country -pincode            ", FontFactory.getFont(FontFactory.COURIER,10, Font.NORMAL, BaseColor.BLACK)));
            cell.addElement(new Paragraph("                                     Ph: 00000 00000                                     ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            cell.setMinimumHeight(60);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell);
            document.add(table);
            table = new PdfPTable(6);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{3, 4,1,6, 4,3});
            table.setWidthPercentage(100);
            PdfPCell cell1 = new PdfPCell(new Phrase("State Code", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("    State", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase(" 00", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase());
            cell1.setRowspan(2);
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("Purchase No. ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase(purnumber, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("GSTIN", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("XXXXXXXXXAAAAAA", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1.setColspan(2);
            //table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase("Purchase Date", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            cell1 = new PdfPCell(new Phrase(purdate, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell1);
            //cell.addElement(new Paragraph("State Code", FontFactory.getFont(FontFactory.COURIER,10, Font.NORMAL, BaseColor.BLACK)));
            cell1.setMinimumHeight(10);
            cell1.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell1);
            document.add(table);
            table = new PdfPTable(5);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{2, 3,5, 3,2});
            table.setWidthPercentage(100);
            PdfPCell cell2 = new PdfPCell(new Phrase("PAN", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase("  XXXXXXXXX ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase("       PURCHASE INVOICE  ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase());
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase());
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase("RB Lic No:", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase("   D XXXXXXX", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase("   TRIPLICATE FOR SUPPLIER   ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase());
            table.addCell(cell2);
            cell2 = new PdfPCell(new Phrase());
            table.addCell(cell2);
            cell2.setMinimumHeight(10);
            cell2.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell2);
            document.add(table);
            table = new PdfPTable(2);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{5,5});
            table.setWidthPercentage(100);
            PdfPCell cell3 = new PdfPCell(new Phrase("            Details of Supplier                ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell3);
            cell3 = new PdfPCell(new Phrase("              Shipped From                ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell3);
            cell3.setMinimumHeight(10);
            cell3.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell3);
            document.add(table);
               table = new PdfPTable(2);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{5,5});
            table.setWidthPercentage(100);
            
            PdfPCell cell4 = new PdfPCell(new Phrase("\n"+name+"\n"+detailsupp+"\n ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell4);
             
           
          
            cell4 = new PdfPCell(new Phrase("\n"+shippedfrom+"\n", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell4);
            
            cell4.setMinimumHeight(60);
            document.add(table);
            table = new PdfPTable(4);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{2,6,2,6});
            table.setWidthPercentage(100);
            PdfPCell cell5 = new PdfPCell(new Phrase("GSTIN ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(""));
            table.addCell(cell5);
            cell5 = new PdfPCell(new Phrase("GSTIN ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(""));
            table.addCell(cell5);
            cell5.setMinimumHeight(10);
            cell5.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell4);
            document.add(table);
            table = new PdfPTable(6);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{2,5,1,2,5,1});
            table.setWidthPercentage(100);
            PdfPCell cell6 = new PdfPCell(new Phrase("State Code ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(""));
            table.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(""));
            table.addCell(cell6);
            cell6 = new PdfPCell(new Phrase("State Code ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(""));
            table.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(""));
            table.addCell(cell6);
            cell6.setMinimumHeight(10);
            cell6.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell6);
            document.add(table);
            table = new PdfPTable(8);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{2, 1,1, 1,1,1,1,1});
            table.setWidthPercentage(100);
            PdfPCell cell7 = new PdfPCell(new Phrase(" Commodity Code", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" HSN Code ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Barrels", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("    Wet\n  Wt.(Kg)", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("   DRC % ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("   DRC\n  Wt/Kgs", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("   Rate ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Total\n Value", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+commoditycode, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+hsncode, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+noofbarrels, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+wetwg, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+drc, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(drcwtkgs, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+rate, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(total, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell7);
            
            //cell.addElement(new Paragraph("State Code", FontFactory.getFont(FontFactory.COURIER,10, Font.NORMAL, BaseColor.BLACK)));
            cell7.setMinimumHeight(10);
            cell7.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell7);
            document.add(table); 
            table = new PdfPTable(3);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{6,2,1});
            table.setWidthPercentage(100);
            PdfPCell cell8 = new PdfPCell(new Phrase("                                                                         ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
             cell8.setRowspan(2);
            table.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" Total ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(total, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell8);    
            cell8 = new PdfPCell(new Phrase(" Round Off ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" 0.00 ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table.addCell(cell8);
            cell8.setMinimumHeight(20);
            cell8.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell8);
            document.add(table);
            
            table = new PdfPTable(3);
//            table.setSpacingBefore(5);
            table.setWidths(new int[]{6,2,1});
            table.setWidthPercentage(100);
            String grandtotal="";
            int numLength = total.length();
            String numberToWord = "";
                    for (int j = 0; j < numLength; j++) {

            switch (total.charAt(j)) {

                case '1': {  
                    numberToWord = numberToWord + "One"+ " ";
                    grandtotal=grandtotal+"1";
                    break;
                }
                case '2': { 
                    numberToWord = numberToWord + "Two"+ " ";
                    grandtotal=grandtotal+"2";
                    break;
                }
                case '3': {
                    numberToWord = numberToWord + "Three" + " ";
                    grandtotal=grandtotal+"3";
                    break;
                }
                case '4': {
                    numberToWord = numberToWord + "Four"+" ";
                    grandtotal=grandtotal+"4";
                    break;
                }
                case '5': {
                    numberToWord = numberToWord + "Five"+" ";
                    grandtotal=grandtotal+"5";
                    break;
                }
                case '6': {
                    numberToWord = numberToWord + "Six"+" ";
                    grandtotal=grandtotal+"6";
                    break;
                }
                case '7': {
                    numberToWord = numberToWord + "Seven"+" ";
                    grandtotal=grandtotal+"7";
                    break;
                }
                case '8': {
                    numberToWord = numberToWord + "Eight"+" ";
                    grandtotal=grandtotal+"8";
                    break;
                }
                case '9': {
                    numberToWord = numberToWord + "Nine"+" ";
                    grandtotal=grandtotal+"9";
                    break;
                }
                case '0': {
                    numberToWord = numberToWord + "Zero"+" ";
                    grandtotal=grandtotal+"0";
                    break;
                }
                default: {
                    j=j+25;
                     break;
                }
            }
        }
            PdfPCell cell9 = new PdfPCell(new Phrase(" Rs:(in Words):" +numberToWord+ "Only ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell9.setRowspan(3);
            table.addCell(cell9);
            cell9 = new PdfPCell(new Phrase(" Grand Total ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell9);
            cell9 = new PdfPCell(new Phrase(" "+grandtotal, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table.addCell(cell9);
            cell9 = new PdfPCell(new Phrase("      For xxxxx XXXXXXX                  \n\n\n\n     Authorized Signatory", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell9.setRowspan(2);
            cell9.setColspan(2);
            table.addCell(cell9);
            cell9.setMinimumHeight(20);
            cell9.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table.addCell(cell9);
            document.add(table);

            document.close();
            
        }catch(DocumentException | FileNotFoundException e){
            JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(null, "Doccument Cannot Open");
                    
        }
         if (Desktop.isDesktopSupported()) {
    try {
        
        File myFile = new File("pdfresult/result.pdf");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null,ex);
    }
         } 
         try {
             conn.close();
         } catch (SQLException ex) {
             Logger.getLogger(farmerpurchase.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
       String dr = this.jTextField6.getText();
        String wet = this.jTextField5.getText();
        double bb=Double.parseDouble(dr);
        double aa=Double.parseDouble(wet);
        double res=aa*bb/100;
        jTextField7.setText(String.valueOf(res));
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
       String dr = this.jTextField6.getText();
        String wet = this.jTextField5.getText();
        String rate=this.jTextField8.getText();
        double bb=Double.parseDouble(dr);
               
        double aa=Double.parseDouble(wet);
        double res=aa*bb/100;
        double tot;
        tot =Double.parseDouble(rate);
        double total=(double) (tot*res);
        jTextField10.setText(String.valueOf(total));
        
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
     
        try{
            conn = dbconnection.getConnected();
    
            String value=jComboBox1.getSelectedItem().toString();   
             Statement st2 = conn.createStatement();
             ResultSet rs2;
             rs2 = st2.executeQuery("SELECT * FROM  commoditycode WHERE commoditycode='"+value+"'");
             if(rs2.last()){  
             jTextField3.setText(rs2.getString("hsncode"));
             
             }conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }   
      
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
     
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new farmerpurchaselist().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new salesdealer().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      new addstate().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new salesuser().setVisible(true); 
        dispose();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
 
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
            conn = dbconnection.getConnected();
            String value=this.jTextField9.getText(); 
//            String[] myName = value.split("");
            try{
                          
             Statement st2 = conn.createStatement();
             //ResultSet rs2;
             String sql = "SELECT name FROM  adduser WHERE name LIKE ?";
             PreparedStatement ps = conn.prepareStatement(sql);
             ps.setString(1, "%" + value + "%");
             ResultSet rs2 = ps.executeQuery();
             //rs2 = st2.executeQuery(sql);
                     
              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
               model.setRowCount(0);
             while (rs2.next()){  
               String name=rs2.getString("name");
               model.addRow(new Object[]{name});
             }conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }    
        
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
       
        int i=jTable1.getSelectedRow();  
        String value1=jTable1.getModel().getValueAt(i, 0).toString();
        jTextField9.setText(value1); 
         conn = dbconnection.getConnected();
            
            try{
                          
             Statement st2 = conn.createStatement();
             ResultSet rs2;
             String sql = "SELECT * FROM  adduser WHERE name ='"+value1+"'";
             rs2 = st2.executeQuery(sql);
    
            if(rs2.last()){  
              jTextArea1.setText(rs2.getString("supplier"));
              jTextArea2.setText(rs2.getString("shipped"));
             }conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }    
        
    }//GEN-LAST:event_jTable1MousePressed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
//        jTextField4.addKeyListener(new KeyAdapter() {});
//    char char_input = evt.getKeyChar();
//    if (((char_input < '0') || (char_input > '9')) && (char_input != '\b'))
//    {
//        JOptionPane.showMessageDialog(this, "Number only!","Invalid Input",JOptionPane.ERROR_MESSAGE);
//        jTextField4.setText(" ");
//    }
    }//GEN-LAST:event_jTextField4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new userhome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

     
}
