/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jojo
 */
public class salesdealer extends javax.swing.JFrame {

    /**
     * Creates new form userhome
     */
     Connection conn=null;
    Date date = new Date();
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
 
        //to convert Date to String, use format method of SimpleDateFormat class.
        String strDate = dateFormat.format(date);
    public salesdealer() {
        initComponents();
         jTextField1.setText(strDate); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField21 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rb.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iso.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1225, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("LOGOUT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel35.setText("Dealer Sales");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("FARMER PURCHASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PURCHASE");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SALES");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("DEALER SALES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USER");

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("HOME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("FARMER PURCHASE LIST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("DEALER SALES LIST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("ADD FARMER USER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setText("ADD SALES USER");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(45, 45, 45))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Sale Date");

        jTextField1.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Sales Number");

        jTextField2.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Details of Reciver");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Details of Consignee");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Commodity Code");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("HSN Code");

        jTextField3.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Number of Barrels");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Qty. Ltrs");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("DRC Qnty/KGS");

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Qnty. Kg");

        jTextField7.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Rate");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Total");

        jTextField9.setEditable(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 204, 51));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Reciver Bill State");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Shipped To Bill State");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Reciver GST Number");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Shipped (GST NO.)");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Name");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Mobile Number");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("PAN Number");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("RBL Number");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Mobile Number");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("PAN Number");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("RBL Number");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("State Code");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("State Code");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Taxable Value");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CGST/SCGST", "IGST" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField14)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField8)
                                    .addComponent(jComboBox4, 0, 147, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jTextField17)
                                    .addComponent(jTextField23))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15))
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(79, 79, 79)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel24)
                                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(49, 49, 49))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(88, 88, 88)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(25, 25, 25)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton9)
                                    .addComponent(jButton8))
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new userhome().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       new login().setVisible(true); 
       dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new farmerpurchase().setVisible(true); 
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new salesdealer().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
    conn = dbconnection.getConnected();
    Statement st =  conn.createStatement();
    Statement st1 = conn.createStatement();
    
            ResultSet rs;
            rs = st.executeQuery("SELECT MAX(slid) FROM salesdealer");
            ResultSet rs1;
            rs1 = st1.executeQuery("SELECT commoditycode  FROM  commoditycode");
            
    if (rs.next()) {
        int billNumber = rs.getInt(1) + 1;
        jTextField2.setText(Integer.toString(billNumber));    
    }
    while ((rs1.next())) {
            jComboBox1.addItem(rs1.getString("commoditycode"));
          }
   
    conn.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
}
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
         String dr = this.jTextField6.getText();
        String wet = this.jTextField5.getText();
        double bb=Integer.parseInt(dr);
        double aa=Integer.parseInt(wet);
        double res=aa*bb/100;
        jTextField7.setText(String.valueOf(res));
        
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
       String dr = this.jTextField6.getText();
        String wet = this.jTextField5.getText();
        String rate=this.jTextField8.getText();
        double bb=Integer.parseInt(dr);
        double aa=Integer.parseInt(wet);
        double res=aa*bb/100;
        double tot;
        tot = Integer.parseInt(rate);
        double total=(double) (tot*res);
        jTextField9.setText(String.valueOf(total));
        
        
        
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            jTextField1.setText(strDate);
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextArea1.setText("");
            jTextArea2.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            jTextField16.setText("");
            jTextField17.setText("");
            jTextField18.setText("");
            jTextField19.setText("");
            jTextField20.setText("");
            jTextField21.setText("");
            jTextField23.setText("");
//           

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        conn = dbconnection.getConnected();
        String name,detailreciver,billmobno,billpanno,billrblno,billstate,billgstno,billstatecode,shippedto,smobno,spanno,srblno,sstate,sgstno,sstatecode,saledate,salenumber,commoditycode,hsncode,noofbarrels,qntyltrs,drckgs,qntykgs,rate,total,amountpayed,taxableval;
        name=this.jTextField12.getText();
        detailreciver = this.jTextArea1.getText();
        billmobno=this.jTextField13.getText();
        billpanno=this.jTextField14.getText();
        billrblno=this.jTextField15.getText();
        billstate=this.jTextField21.getText();
        billgstno= this.jTextField10.getText();
        billstatecode=this.jTextField20.getText();
        shippedto = this.jTextArea2.getText();
        smobno=this.jTextField16.getText();
        spanno=this.jTextField17.getText();
        srblno=this.jTextField18.getText();
        sstate=this.jTextField23.getText();
        sgstno = this.jTextField11.getText();
        sstatecode=this.jTextField19.getText();
        
        saledate =this.jTextField1.getText();
        salenumber = this.jTextField2.getText();
        commoditycode=(String) this.jComboBox1.getSelectedItem();
        hsncode=this.jTextField3.getText();
        noofbarrels=this.jTextField4.getText();
        qntyltrs = this.jTextField5.getText();
        drckgs = this.jTextField6.getText();
        qntykgs=this.jTextField7.getText();
        rate=this.jTextField8.getText();
        total=this.jTextField9.getText();
        taxableval=(String) this.jComboBox4.getSelectedItem();
        amountpayed="0";
        String query;
        try {
            query = "insert into salesdealer(name,saledate,salenumber,detailreciver,detailconsignee,commoditycode,hsncode,noofbarrels,qntyltrs,drckgs,qntykgs,rate,total,taxablevalue,amountpayed)  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst= conn.prepareStatement(query);
            pst.setString(1,name);
            pst.setString(2,saledate);
            pst.setString(3,salenumber);
            pst.setString(4,detailreciver);
            pst.setString(5,shippedto);
            pst.setString(6,commoditycode);
            pst.setString(7,hsncode);
            pst.setString(8,noofbarrels);
            pst.setString(9,qntyltrs);
            pst.setString(10,drckgs);
            pst.setString(11,qntykgs);
            pst.setString(12,rate);
            pst.setString(13,total);
            pst.setString(14,taxableval);
            pst.setString(15,amountpayed);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Updated");
            jTextField1.setText("");
            int purnumnext=Integer.parseInt(salenumber)+1;
            jTextField2.setText(Integer.toString(purnumnext));
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            jTextArea1.setText("");
            jTextArea2.setText("");
            jTextField16.setText("");
            jTextField17.setText("");
            jTextField18.setText("");
            jTextField19.setText("");
            jTextField20.setText("");
            jTextField21.setText("");
            jTextField23.setText("");
            jTextField1.setText(strDate);
            

        } catch (SQLException ex) {
            Logger.getLogger(farmerpurchase.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Please Insert Value");
        }
        
        
                  
        try{
            Document document=new Document();
            PdfWriter.getInstance(document, new FileOutputStream("pdfresult/resultsales.pdf"));
            document.open();
            Paragraph paragraph = new Paragraph("DUPLICATE ", FontFactory.getFont(FontFactory.COURIER   ,16, Font.BOLD, BaseColor.BLACK));
            paragraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(paragraph);
            Paragraph para1 = new Paragraph("Asian Latex ", FontFactory.getFont(FontFactory.TIMES_ROMAN,20, Font.BOLD, BaseColor.BLACK));
            para1.setAlignment(Element.ALIGN_CENTER);
            document.add(para1);
            Paragraph para2 = new Paragraph("Thannickal Buildings, Mukkoottuthara P.O, ", FontFactory.getFont(FontFactory.COURIER,10, BaseColor.BLACK));
            para2.setAlignment(Element.ALIGN_CENTER);
            document.add(para2);
            Paragraph para3 = new Paragraph("Kottayam Distritc, Kerala, India-686510 ", FontFactory.getFont(FontFactory.COURIER,10, BaseColor.BLACK));
            para3.setAlignment(Element.ALIGN_CENTER);
            document.add(para3);
            Paragraph para4 = new Paragraph("Phone : 0482 8254012", FontFactory.getFont(FontFactory.COURIER,10, BaseColor.BLACK));
            para4.setAlignment(Element.ALIGN_CENTER);
            document.add(para4);
                     
            PdfPTable table1=new PdfPTable(4);
            table1.setWidths(new int[]{2,2,1,10});
            table1.setWidthPercentage(100);
            table1.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cellt1 = new PdfPCell(new Phrase("State Code", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt1);
            cellt1 = new PdfPCell(new Phrase(" Kerala", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt1);
            cellt1 = new PdfPCell(new Phrase(" 32", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt1);
            cellt1 = new PdfPCell(new Phrase());
            cellt1.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cellt1);
            
            cellt1.setPaddingLeft(-50);
            document.add(table1);
            
            table1=new PdfPTable(4);
            table1.setWidths(new int[]{2,3,6,4});
            table1.setWidthPercentage(100);
            table1.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cellt3 = new PdfPCell(new Phrase("GST No:", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt3);
            cellt3 = new PdfPCell(new Phrase(" 32AGHPJ7696Q1ZJ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt3);
            cellt3 = new PdfPCell(new Phrase());
            cellt3.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cellt3);
            cellt3 = new PdfPCell(new Phrase(" Reverse Charge: NO", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cellt3.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cellt3);
            cellt3.setPaddingLeft(-50);
            document.add(table1);
            
            table1 = new PdfPTable(5);
            table1.setWidths(new int[]{2,3,5,3,2});
            table1.setWidthPercentage(100);
            table1.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cellt2 = new PdfPCell(new Phrase("PAN", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(" AGHIPJ7696Q", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase("    TAX INVOICE", FontFactory.getFont(FontFactory.COURIER ,16, Font.BOLD,  BaseColor.BLACK)));
            cellt2.setRowspan(2); 
            cellt2.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(" Invoice No:", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(" AL-013-"+salenumber, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase("RB L No:", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(" D 1430936", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(" Invoice Date", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            cellt2 = new PdfPCell(new Phrase(saledate, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cellt2);
            
            cellt2.setMinimumHeight(10);
            document.add(table1);
            Paragraph para5 = new Paragraph("(Under Rule 46 of GST Invoice Rules, 2017) ", FontFactory.getFont(FontFactory.COURIER,7, Font.NORMAL, BaseColor.BLACK));
            para5.setAlignment(Element.ALIGN_CENTER);
            document.add(para5);
            table1.setSpacingBefore(30);
            table1 = new PdfPTable(1);
            table1.setWidthPercentage(100);
             PdfPCell cellt4 = new PdfPCell(new Phrase());
             cellt4.setVerticalAlignment(Element.ALIGN_MIDDLE); 
             cellt4.setBorder(Rectangle.NO_BORDER);
             cellt4.setMinimumHeight(30);
            table1.addCell(cellt4);

            document.add(table1);
            
            
           table1=new PdfPTable(2);
            
            table1.setWidthPercentage(100);
                         
            PdfPCell cellt5=new PdfPCell(new Phrase("     Details of Receiever (Billed To)                ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cellt5);
            cellt5 = new PdfPCell(new Phrase("      Details of Cosignee (Shipped To)                ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cellt5);
            cellt5.setMinimumHeight(10);
            cellt5.setVerticalAlignment(Element.ALIGN_UNDEFINED); 
            document.add(table1);
           
            table1 = new PdfPTable(2);
            //table1.setSpacingBefore(5);
            table1.setWidths(new int[]{5,5});
            table1.setWidthPercentage(100);
            PdfPCell cell4 = new PdfPCell(new Phrase("\n"+detailreciver+"\n ", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            table1.addCell(cell4);
//            cell4 = new PdfPCell(new Phrase());
//            table1.addCell(cell4);
            cell4 = new PdfPCell(new Phrase("\n"+shippedto+"\n", FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            table1.addCell(cell4);
            cell4.setMinimumHeight(60);
            document.add(table1);
            table1 = new PdfPTable(4);
//            table.setSpacingBefore(5);
            table1.setWidths(new int[]{4,4,4,4});
            table1.setWidthPercentage(100);
            PdfPCell cell5 = new PdfPCell(new Phrase(" Mob No: "+billmobno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" PAN No: "+billpanno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" Mob No: "+smobno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" PAN No: "+spanno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" RBL No: "+billrblno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" State : "+billstate, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" RBL No: "+srblno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5 = new PdfPCell(new Phrase(" State : "+sstate, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell5);
            cell5.setMinimumHeight(10);
            cell5.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table1.addCell(cell4);
            document.add(table1);
            table1 = new PdfPTable(8);
//           table.setSpacingBefore(5);
            table1.setWidths(new int[]{1,3,2,1,1,3,2,1});
            table1.setWidthPercentage(100);
            PdfPCell cell6 = new PdfPCell(new Phrase(" GST\n NO", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" "+billgstno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" State Code", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" "+billstatecode, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" GST\n NO", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" "+sgstno, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" State Code", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            cell6 = new PdfPCell(new Phrase(" "+sstatecode, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell6);
            
            document.add(table1);
            // table1.setSpacingBefore(5);
            
                        
            table1 = new PdfPTable(8);
//            table.setSpacingBefore(5);
            table1.setWidths(new int[]{2, 1,1, 1,1,1,1,1});
            table1.setWidthPercentage(100);
            table1.setSpacingBefore(20);
            PdfPCell cell7 = new PdfPCell(new Phrase(" Commodity Code/Item", FontFactory.getFont(FontFactory.COURIER ,9, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" HSN Code ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Barrels", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Qty.Ltrs", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" DRC Qty ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Qty.Kg", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Rate/KG ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(" Taxable Value", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+commoditycode, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+hsncode, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+noofbarrels, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+qntyltrs, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+drckgs, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase(qntykgs, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            cell7 = new PdfPCell(new Phrase("  "+rate, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            String totalsum="0";
            totalsum= String.valueOf(total).split("\\.")[0];
            cell7 = new PdfPCell(new Phrase(" "+totalsum, FontFactory.getFont(FontFactory.COURIER ,10, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell7);
            
            //cell.addElement(new Paragraph("State Code", FontFactory.getFont(FontFactory.COURIER,10, Font.NORMAL, BaseColor.BLACK)));
            cell7.setMinimumHeight(10);
            cell7.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table1.addCell(cell7);
            document.add(table1); 
            float totalint=0;
            float igst=0;
            float cgst=0;         
            totalint=Float.parseFloat(total);
            float totalsu=0;
            if("IGST".equals(taxableval)){
                igst=(float) (totalint*(5/100));
                 totalsu=totalsu+igst;               
            }else{
                 cgst=(float) (totalint*(2.5/100));
                 totalsu=totalsu+cgst+cgst;
             }
            totalsu=totalsu+totalint;
                        
//            String tot="0";
//            tot=String.valueOf(totalsu).split("\\.")[0];
            
            
            table1 = new PdfPTable(4);
//            table.setSpacingBefore(5);
            table1.setWidths(new int[]{5,2,1,1});
            table1.setWidthPercentage(100);
            PdfPCell cell8 = new PdfPCell(new Phrase());
             cell8.setRowspan(6);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" CGST % ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
             cell8.setColspan(1);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase());
            table1.addCell(cell8);    
            cell8 = new PdfPCell(new Phrase(" "+cgst, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" SGST % ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell8.setColspan(1);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase());
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" "+cgst, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" IGST 5 % ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell8.setColspan(1);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase());
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" "+igst, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" Round off        ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell8.setColspan(1);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase());
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" 0.00 ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" Total", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            cell8.setColspan(2);
            table1.addCell(cell8);
            cell8 = new PdfPCell(new Phrase(" "+totalsu, FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell8);
            cell8.setMinimumHeight(20);
            cell8.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table1.addCell(cell8);
            document.add(table1);
            
            table1 = new PdfPTable(1);
//            table.setSpacingBefore(5);
            //table1.setWidths(new int[]{10});
            table1.setWidthPercentage(100);
            String grandtotal="";
//            String total="369";
            int numLength = total.length();
            String numberToWord = "";
                    for (int j = 0; j < numLength; j++) {

            switch (total.charAt(j)) {

                case '1': {  
                    numberToWord = numberToWord + "One"+ " ";
                    grandtotal=grandtotal+"1";
                    break;
                }
                case '2': { 
                    numberToWord = numberToWord + "Two"+ " ";
                    grandtotal=grandtotal+"2";
                    break;
                }
                case '3': {
                    numberToWord = numberToWord + "Three" + " ";
                    grandtotal=grandtotal+"3";
                    break;
                }
                case '4': {
                    numberToWord = numberToWord + "Four"+" ";
                    grandtotal=grandtotal+"4";
                    break;
                }
                case '5': {
                    numberToWord = numberToWord + "Five"+" ";
                    grandtotal=grandtotal+"5";
                    break;
                }
                case '6': {
                    numberToWord = numberToWord + "Six"+" ";
                    grandtotal=grandtotal+"6";
                    break;
                }
                case '7': {
                    numberToWord = numberToWord + "Seven"+" ";
                    grandtotal=grandtotal+"7";
                    break;
                }
                case '8': {
                    numberToWord = numberToWord + "Eight"+" ";
                    grandtotal=grandtotal+"8";
                    break;
                }
                case '9': {
                    numberToWord = numberToWord + "Nine"+" ";
                    grandtotal=grandtotal+"9";
                    break;
                }
                case '0': {
                    numberToWord = numberToWord + "Zero"+" ";
                    grandtotal=grandtotal+"0";
                    break;
                }
                default: {
                    j=j+25;
                     break;
                }
            }
        }
            PdfPCell cell9 = new PdfPCell(new Phrase(" Invoice Value in Words(Rupees):" +numberToWord+ "Only\n ", FontFactory.getFont(FontFactory.COURIER ,10, Font.BOLD, BaseColor.BLACK)));
            table1.addCell(cell9);
            document.add(table1);
                        
            table1 = new PdfPTable(2);
            
            table1.setWidths(new int[]{5,5});
            table1.setWidthPercentage(100);
            PdfPCell cell10 = new PdfPCell(new Phrase(" Given below is our bank details for making RTGS/NEFT\n\n A/c Name  : ASIAN LATEX\n A/c No    : 67295447136 \n Bank Name : State Bank of India\n Branch    : Erumeli\n IFSC Code : SBIN0070105\n\n\n", FontFactory.getFont(FontFactory.COURIER ,8, Font.BOLD, BaseColor.BLACK)));
            cell10.setRowspan(2);
            table1.addCell(cell10);
            cell10 = new PdfPCell(new Phrase(" Transportation by: \n\n LR No            : \n DL Number        :\n Driver Name      : \n Vechicle No      : KL34F1079\n ", FontFactory.getFont(FontFactory.COURIER ,8, Font.NORMAL, BaseColor.BLACK)));
             table1.addCell(cell10);
             
            cell10 = new PdfPCell(new Phrase("             Terms of Delivery, if any\n\n\n\n", FontFactory.getFont(FontFactory.COURIER ,8, Font.NORMAL, BaseColor.BLACK)));
            table1.addCell(cell10);
           // table1.setSpacingBefore(8);
            document.add(table1);
            
            table1 = new PdfPTable(2);
            table1.setWidths(new int[]{6,5});
            table1.setWidthPercentage(100);
            cell10 = new PdfPCell(new Phrase(" Confirmed that all particulars given above are true and correct                       \n\n\n\n\n\n\n\n                  Seal", FontFactory.getFont(FontFactory.COURIER ,7, Font.BOLD, BaseColor.BLACK)));
             cell10.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cell10);
            cell10 = new PdfPCell(new Phrase("                          For ASIAN LATEX  \n\n\n\n\n \n                      Authorized Signatory", FontFactory.getFont(FontFactory.COURIER ,9, Font.BOLD, BaseColor.BLACK)));
             cell10.setBorder(Rectangle.NO_BORDER);
            table1.addCell(cell10);
            cell10.setMinimumHeight(10);
            cell10.setVerticalAlignment(Element.ALIGN_MIDDLE); 
            table1.addCell(cell10);
            document.add(table1);

            document.close();
            
        }catch(DocumentException | FileNotFoundException e){
            JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(null, "Doccument Cannot Open");
                    
        }
         if (Desktop.isDesktopSupported()) {
    try {
        
        File myFile = new File("pdfresult/resultsales.pdf");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null,ex);
    }
         } 
        
        
         try {
             conn.close();
         } catch (SQLException ex) {
             Logger.getLogger(salesdealer.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
              try{
            conn = dbconnection.getConnected();
    
            String value=jComboBox1.getSelectedItem().toString();   
             Statement st2 = conn.createStatement();
             ResultSet rs2;
             rs2 = st2.executeQuery("SELECT * FROM  commoditycode WHERE commoditycode='"+value+"'");
             if(rs2.last()){  
             jTextField3.setText(rs2.getString("hsncode"));
             }conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }   
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new farmerpurchaselist().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new dealersaleslist().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new addstate().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new salesuser().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        conn = dbconnection.getConnected();
        String value=this.jTextField12.getText();
        //            String[] myName = value.split("");
        try{

            //Statement st2 = conn.createStatement();
            //ResultSet rs2;
            String sql = "SELECT name FROM  addsaleuser WHERE name LIKE ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "%" + value + "%");
            ResultSet rs2 = ps.executeQuery();
            //rs2 = st2.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while (rs2.next()){
                String name=rs2.getString("name");
                model.addRow(new Object[]{name});
            }conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int i=jTable1.getSelectedRow();  
        String value1=jTable1.getModel().getValueAt(i, 0).toString();
        jTextField12.setText(value1); 
         conn = dbconnection.getConnected();
            
            try{
                          
             Statement st2 = conn.createStatement();
             ResultSet rs2;
             String sql = "SELECT * FROM  addsaleuser WHERE name ='"+value1+"'";
             rs2 = st2.executeQuery(sql);
    
            if(rs2.last()){  
              jTextField12.setText(rs2.getString("name"));
              jTextArea1.setText(rs2.getString("billedto"));
              jTextField13.setText(rs2.getString("billmobno"));
              jTextField14.setText(rs2.getString("billpanno"));
              jTextField15.setText(rs2.getString("billrblno"));
              jTextField21.setText(rs2.getString("billstate"));
              jTextField10.setText(rs2.getString("billgstno"));
              jTextField20.setText(rs2.getString("billstatecode"));
              jTextArea2.setText(rs2.getString("shippedto"));
              jTextField16.setText(rs2.getString("smobno"));
              jTextField17.setText(rs2.getString("spanno"));
              jTextField18.setText(rs2.getString("srblno"));
              jTextField23.setText(rs2.getString("sstate"));
              jTextField11.setText(rs2.getString("sgstno"));
              jTextField19.setText(rs2.getString("sstatecode"));
             }conn.close();
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, ex.toString());
    }   
        
    }//GEN-LAST:event_jTable1MousePressed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
